### ISSUE TITLE
in_app_purchase (subscription): Couldn't find purchase lists, trying to find single data.

### ISSUE THREAD

**Issue by mdmota** [RobertBrunhage/flutter-riverpod-snippets#10]
the thread was closed , so i'll send it here
 I think I got it here.
I commented the subscription.cancel of the screen that makes the subscription and moved it to the main dispose.
After that all my tests passed successfully.
Please validate.

PremiumPage.dart
  ```
@override
   void dispose() {
     //subscriptionMobxController.subscription!.cancel();
     super.dispose();
   }
```

Main.dart
```
@override
   void dispose() {
     endController Signature MobxController Signature = GetIt.I<Controller Signature>();
     if (Platform.isIOS) {
       var iosPlatformAddition = signature MobxController.inAppPurchase
           .getPlatformAddition<InAppPurchaseIosPlatformAddition>();
       iosPlatformAddition.setDelegate(null);
     }
     subscription MobxController.subscription?.cancel();
     super.dispose();
   }
```

**Comment by pythonhubpy** [comment]
Is this related to riverpod snippets??

**Comment by RobertBrunhage** [comment]
Not related, closing.

**Comment by mdmota** [comment]
You opened this thread in 2019 https://github.com/flutter/flutter/issues/35741 and got no response. Looks like I figured out where the problem might be. As I didn't see another way to get in touch with you, I put it here. Can you reopen it from there?

**Comment by RobertBrunhage** [comment]
@mdmota ahh I see, sadly I can't reopen that issue
