### ISSUE TITLE
Shortcut `stfulConsumer` is not working.

### ISSUE THREAD

**Issue by kokikudo** [RobertBrunhage/flutter-riverpod-snippets#11]
https://user-images.githubusercontent.com/51766366/144686627-28a531ba-e9e3-4b0f-b95c-b59eaac2cce2.mov

**Comment by RobertBrunhage** [comment]
Thanks for finding the issue @kokikudo. I am currently building and publishing a new version, I will close when either you or I can verify it on the new `1.0.1` version

**Comment by RobertBrunhage** [comment]
Verified and now works!

**Comment by pcelis19** [comment]
1

> Verified and now works!

I don't think it works. I have tried a lot of times with different permutations, and I cannot get the snippet to work for me. 

![bug](https://user-images.githubusercontent.com/34390914/148170821-37c64896-f69a-43c9-af00-bc4226600846.gif)

**Comment by RobertBrunhage** [comment]
@pcelis19 at the beginning with the version of the extension it looks like you are using `v1.0.0` but it should be `v1.0.1`. Update it and let me know if it works!

**Comment by pcelis19** [comment]
@RobertBrunhage So it started working on Windows. I started working on my Mac and the same issue occurred, and I looked at the available versions on VS code, and it only goes up to `1.0.0` not `1.0.1`
