### ISSUE TITLE
Auto import Riverpod when using Riverpod snippets

### ISSUE THREAD

**Issue by FXschwartz** [RobertBrunhage/flutter-riverpod-snippets#12]
Not a big deal but a nice to have would be when using a snippet, it also auto imported the flutter riverpod package for you to save you an extra step.

https://user-images.githubusercontent.com/16527593/150360171-a669a9dc-6d62-45fa-ba2c-38d4743d67d7.mov

**Comment by RobertBrunhage** [comment]
Have not found if this is possible.

Of course, it **could** be added as part of the snippet but that would break the usage anytime you do not have an empty file.

If you are aware of a solution, let me know!

**Comment by pythonhubpy** [comment]
Can we have a snippet that can import `riverpod` like `riverImport` but I feel like this very simple to import even by typing without snippet.  Is there any other way to do this kind of thing in vs code snippet @RobertBrunhage

**Comment by RobertBrunhage** [comment]
@pythonhubpy  I don't feel like that is needed, and I am not aware of a different solution

**Comment by pythonhubpy** [comment]
> @pythonhubpy I don't feel like that is needed, and I am not aware of a different solution

Okay will check if there is any other methods with which we can do
