### ISSUE TITLE
Convert to ({super.key})

### ISSUE THREAD

**Issue by decadentsavant** [RobertBrunhage/flutter-riverpod-snippets#24]
As of Dart 2.17 you can pass constructor parameters to the superclass with the new shorthand syntax. It would be nice if the snippets transitioned to this new syntax for the 'key' args.

https://dart-lang.github.io/linter/lints/use_super_parameters.html

**Comment by RobertBrunhage** [comment]
On vacation now but I agree! Would love to get a PR for it if you are able to 😎

**Comment by decadentsavant** [comment]
Done...maybe?

1) I'm self-taught, relatively inexperienced, and always worked alone. I literally had to google "how to do a pull request."
2) I just inferred from the JSON snippets what was happening under the hood here; I've never seen this before.

Would love some feedback to let me know what I did correct, what I need to redo, or what I should do differently in the future. Thanks!
