### ISSUE TITLE
Support quick fixes

### ISSUE THREAD

**Issue by Merrit** [RobertBrunhage/flutter-riverpod-snippets#28]
Are there any plans to support quick fixes [like what bloc does?](https://marketplace.visualstudio.com/items?itemName=FelixAngelov.bloc)

![image](https://user-images.githubusercontent.com/9575627/196272526-efcefdee-147d-49a0-9f52-801f49f4741f.png)

**Comment by RobertBrunhage** [comment]
Hi!

No, sorry. This extension is purely for snippets. Having VSCode specific integration like shown above is out of scope for this one.
