### ISSUE TITLE
Convert to consumer widget

### ISSUE THREAD

**Issue by ValentinVignal** [RobertBrunhage/flutter-riverpod-snippets#31]
It would be nice to have a command to convert `StatelessWidget` to `ConsumerWidget` and `StatefulWidget` to `ConsumerStatefulWidget`

**Comment by RobertBrunhage** [comment]
I recommend having another extension for VSCode specific integration. I haven't used VSCode in over a year now.

This project is only geared towards snippets, so will close for now but thanks for the issue!
